# Generated by Django 5.1.1 on 2024-10-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mentorprofile_gender_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
