# Generated by Django 5.1.1 on 2024-10-16 08:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_expected_graduation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
