# Generated by Django 5.1.1 on 2024-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mentorprofile_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
